package cn.taiqiu8.model;

public class AssistEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_evaluation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_evaluation.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_evaluation.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    public AssistEvaluation(Integer id, Integer userId, Integer type) {
        this.id = id;
        this.userId = userId;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    public AssistEvaluation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_evaluation.id
     *
     * @return the value of assist_evaluation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_evaluation.id
     *
     * @param id the value for assist_evaluation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_evaluation.user_id
     *
     * @return the value of assist_evaluation.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_evaluation.user_id
     *
     * @param userId the value for assist_evaluation.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_evaluation.type
     *
     * @return the value of assist_evaluation.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_evaluation.type
     *
     * @param type the value for assist_evaluation.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}