package cn.taiqiu8.model;

public class AssistAlbum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_album.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_album.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_album.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_album.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    public AssistAlbum(Integer id, Integer userId, String path, Short status) {
        this.id = id;
        this.userId = userId;
        this.path = path;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    public AssistAlbum() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_album.id
     *
     * @return the value of assist_album.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_album.id
     *
     * @param id the value for assist_album.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_album.user_id
     *
     * @return the value of assist_album.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_album.user_id
     *
     * @param userId the value for assist_album.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_album.path
     *
     * @return the value of assist_album.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_album.path
     *
     * @param path the value for assist_album.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_album.status
     *
     * @return the value of assist_album.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_album.status
     *
     * @param status the value for assist_album.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}