package cn.taiqiu8.model;

public class AssistOrderEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order_evaluation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order_evaluation.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order_evaluation.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    public AssistOrderEvaluation(Integer id, Integer orderId, Integer type) {
        this.id = id;
        this.orderId = orderId;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    public AssistOrderEvaluation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order_evaluation.id
     *
     * @return the value of assist_order_evaluation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order_evaluation.id
     *
     * @param id the value for assist_order_evaluation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order_evaluation.order_id
     *
     * @return the value of assist_order_evaluation.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order_evaluation.order_id
     *
     * @param orderId the value for assist_order_evaluation.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order_evaluation.type
     *
     * @return the value of assist_order_evaluation.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order_evaluation.type
     *
     * @param type the value for assist_order_evaluation.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}