package cn.taiqiu8.model;

public class UserAssist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.assist_acc_time
     *
     * @mbggenerated
     */
    private Integer assistAccTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.audit_status
     *
     * @mbggenerated
     */
    private Short auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.money_input
     *
     * @mbggenerated
     */
    private Integer moneyInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.money_output
     *
     * @mbggenerated
     */
    private Integer moneyOutput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.money_lock
     *
     * @mbggenerated
     */
    private Integer moneyLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.zfb_account
     *
     * @mbggenerated
     */
    private String zfbAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.weixin_account
     *
     * @mbggenerated
     */
    private String weixinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_assist.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public UserAssist(Integer id, Integer userId, Integer assistAccTime, String identityCard, Short auditStatus, Integer moneyInput, Integer moneyOutput, Integer moneyLock, String zfbAccount, String weixinAccount, Short status) {
        this.id = id;
        this.userId = userId;
        this.assistAccTime = assistAccTime;
        this.identityCard = identityCard;
        this.auditStatus = auditStatus;
        this.moneyInput = moneyInput;
        this.moneyOutput = moneyOutput;
        this.moneyLock = moneyLock;
        this.zfbAccount = zfbAccount;
        this.weixinAccount = weixinAccount;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public UserAssist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.id
     *
     * @return the value of user_assist.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.id
     *
     * @param id the value for user_assist.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.user_id
     *
     * @return the value of user_assist.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.user_id
     *
     * @param userId the value for user_assist.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.assist_acc_time
     *
     * @return the value of user_assist.assist_acc_time
     *
     * @mbggenerated
     */
    public Integer getAssistAccTime() {
        return assistAccTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.assist_acc_time
     *
     * @param assistAccTime the value for user_assist.assist_acc_time
     *
     * @mbggenerated
     */
    public void setAssistAccTime(Integer assistAccTime) {
        this.assistAccTime = assistAccTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.identity_card
     *
     * @return the value of user_assist.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.identity_card
     *
     * @param identityCard the value for user_assist.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.audit_status
     *
     * @return the value of user_assist.audit_status
     *
     * @mbggenerated
     */
    public Short getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.audit_status
     *
     * @param auditStatus the value for user_assist.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(Short auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.money_input
     *
     * @return the value of user_assist.money_input
     *
     * @mbggenerated
     */
    public Integer getMoneyInput() {
        return moneyInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.money_input
     *
     * @param moneyInput the value for user_assist.money_input
     *
     * @mbggenerated
     */
    public void setMoneyInput(Integer moneyInput) {
        this.moneyInput = moneyInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.money_output
     *
     * @return the value of user_assist.money_output
     *
     * @mbggenerated
     */
    public Integer getMoneyOutput() {
        return moneyOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.money_output
     *
     * @param moneyOutput the value for user_assist.money_output
     *
     * @mbggenerated
     */
    public void setMoneyOutput(Integer moneyOutput) {
        this.moneyOutput = moneyOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.money_lock
     *
     * @return the value of user_assist.money_lock
     *
     * @mbggenerated
     */
    public Integer getMoneyLock() {
        return moneyLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.money_lock
     *
     * @param moneyLock the value for user_assist.money_lock
     *
     * @mbggenerated
     */
    public void setMoneyLock(Integer moneyLock) {
        this.moneyLock = moneyLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.zfb_account
     *
     * @return the value of user_assist.zfb_account
     *
     * @mbggenerated
     */
    public String getZfbAccount() {
        return zfbAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.zfb_account
     *
     * @param zfbAccount the value for user_assist.zfb_account
     *
     * @mbggenerated
     */
    public void setZfbAccount(String zfbAccount) {
        this.zfbAccount = zfbAccount == null ? null : zfbAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.weixin_account
     *
     * @return the value of user_assist.weixin_account
     *
     * @mbggenerated
     */
    public String getWeixinAccount() {
        return weixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.weixin_account
     *
     * @param weixinAccount the value for user_assist.weixin_account
     *
     * @mbggenerated
     */
    public void setWeixinAccount(String weixinAccount) {
        this.weixinAccount = weixinAccount == null ? null : weixinAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_assist.status
     *
     * @return the value of user_assist.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_assist.status
     *
     * @param status the value for user_assist.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}