package cn.taiqiu8.model;

public class UserCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.money_input
     *
     * @mbggenerated
     */
    private Integer moneyInput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.money_output
     *
     * @mbggenerated
     */
    private Integer moneyOutput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.money_lock
     *
     * @mbggenerated
     */
    private Integer moneyLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_customer
     *
     * @mbggenerated
     */
    public UserCustomer(Integer id, Integer userId, Integer moneyInput, Integer moneyOutput, Integer moneyLock, Integer status) {
        this.id = id;
        this.userId = userId;
        this.moneyInput = moneyInput;
        this.moneyOutput = moneyOutput;
        this.moneyLock = moneyLock;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_customer
     *
     * @mbggenerated
     */
    public UserCustomer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.id
     *
     * @return the value of user_customer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.id
     *
     * @param id the value for user_customer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.user_id
     *
     * @return the value of user_customer.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.user_id
     *
     * @param userId the value for user_customer.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.money_input
     *
     * @return the value of user_customer.money_input
     *
     * @mbggenerated
     */
    public Integer getMoneyInput() {
        return moneyInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.money_input
     *
     * @param moneyInput the value for user_customer.money_input
     *
     * @mbggenerated
     */
    public void setMoneyInput(Integer moneyInput) {
        this.moneyInput = moneyInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.money_output
     *
     * @return the value of user_customer.money_output
     *
     * @mbggenerated
     */
    public Integer getMoneyOutput() {
        return moneyOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.money_output
     *
     * @param moneyOutput the value for user_customer.money_output
     *
     * @mbggenerated
     */
    public void setMoneyOutput(Integer moneyOutput) {
        this.moneyOutput = moneyOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.money_lock
     *
     * @return the value of user_customer.money_lock
     *
     * @mbggenerated
     */
    public Integer getMoneyLock() {
        return moneyLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.money_lock
     *
     * @param moneyLock the value for user_customer.money_lock
     *
     * @mbggenerated
     */
    public void setMoneyLock(Integer moneyLock) {
        this.moneyLock = moneyLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.status
     *
     * @return the value of user_customer.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.status
     *
     * @param status the value for user_customer.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}