package cn.taiqiu8.model;

import java.util.ArrayList;
import java.util.List;

public class UserAssistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public UserAssistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeIsNull() {
            addCriterion("assist_acc_time is null");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeIsNotNull() {
            addCriterion("assist_acc_time is not null");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeEqualTo(Integer value) {
            addCriterion("assist_acc_time =", value, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeNotEqualTo(Integer value) {
            addCriterion("assist_acc_time <>", value, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeGreaterThan(Integer value) {
            addCriterion("assist_acc_time >", value, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("assist_acc_time >=", value, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeLessThan(Integer value) {
            addCriterion("assist_acc_time <", value, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeLessThanOrEqualTo(Integer value) {
            addCriterion("assist_acc_time <=", value, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeIn(List<Integer> values) {
            addCriterion("assist_acc_time in", values, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeNotIn(List<Integer> values) {
            addCriterion("assist_acc_time not in", values, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeBetween(Integer value1, Integer value2) {
            addCriterion("assist_acc_time between", value1, value2, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andAssistAccTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("assist_acc_time not between", value1, value2, "assistAccTime");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNull() {
            addCriterion("identity_card is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNotNull() {
            addCriterion("identity_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardEqualTo(String value) {
            addCriterion("identity_card =", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotEqualTo(String value) {
            addCriterion("identity_card <>", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThan(String value) {
            addCriterion("identity_card >", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThanOrEqualTo(String value) {
            addCriterion("identity_card >=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThan(String value) {
            addCriterion("identity_card <", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThanOrEqualTo(String value) {
            addCriterion("identity_card <=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLike(String value) {
            addCriterion("identity_card like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotLike(String value) {
            addCriterion("identity_card not like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIn(List<String> values) {
            addCriterion("identity_card in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotIn(List<String> values) {
            addCriterion("identity_card not in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardBetween(String value1, String value2) {
            addCriterion("identity_card between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotBetween(String value1, String value2) {
            addCriterion("identity_card not between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Short value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Short value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Short value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Short value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Short value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Short> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Short> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Short value1, Short value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Short value1, Short value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andMoneyInputIsNull() {
            addCriterion("money_input is null");
            return (Criteria) this;
        }

        public Criteria andMoneyInputIsNotNull() {
            addCriterion("money_input is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyInputEqualTo(Integer value) {
            addCriterion("money_input =", value, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputNotEqualTo(Integer value) {
            addCriterion("money_input <>", value, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputGreaterThan(Integer value) {
            addCriterion("money_input >", value, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_input >=", value, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputLessThan(Integer value) {
            addCriterion("money_input <", value, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputLessThanOrEqualTo(Integer value) {
            addCriterion("money_input <=", value, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputIn(List<Integer> values) {
            addCriterion("money_input in", values, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputNotIn(List<Integer> values) {
            addCriterion("money_input not in", values, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputBetween(Integer value1, Integer value2) {
            addCriterion("money_input between", value1, value2, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyInputNotBetween(Integer value1, Integer value2) {
            addCriterion("money_input not between", value1, value2, "moneyInput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputIsNull() {
            addCriterion("money_output is null");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputIsNotNull() {
            addCriterion("money_output is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputEqualTo(Integer value) {
            addCriterion("money_output =", value, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputNotEqualTo(Integer value) {
            addCriterion("money_output <>", value, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputGreaterThan(Integer value) {
            addCriterion("money_output >", value, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_output >=", value, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputLessThan(Integer value) {
            addCriterion("money_output <", value, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputLessThanOrEqualTo(Integer value) {
            addCriterion("money_output <=", value, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputIn(List<Integer> values) {
            addCriterion("money_output in", values, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputNotIn(List<Integer> values) {
            addCriterion("money_output not in", values, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputBetween(Integer value1, Integer value2) {
            addCriterion("money_output between", value1, value2, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyOutputNotBetween(Integer value1, Integer value2) {
            addCriterion("money_output not between", value1, value2, "moneyOutput");
            return (Criteria) this;
        }

        public Criteria andMoneyLockIsNull() {
            addCriterion("money_lock is null");
            return (Criteria) this;
        }

        public Criteria andMoneyLockIsNotNull() {
            addCriterion("money_lock is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyLockEqualTo(Integer value) {
            addCriterion("money_lock =", value, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockNotEqualTo(Integer value) {
            addCriterion("money_lock <>", value, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockGreaterThan(Integer value) {
            addCriterion("money_lock >", value, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_lock >=", value, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockLessThan(Integer value) {
            addCriterion("money_lock <", value, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockLessThanOrEqualTo(Integer value) {
            addCriterion("money_lock <=", value, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockIn(List<Integer> values) {
            addCriterion("money_lock in", values, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockNotIn(List<Integer> values) {
            addCriterion("money_lock not in", values, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockBetween(Integer value1, Integer value2) {
            addCriterion("money_lock between", value1, value2, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andMoneyLockNotBetween(Integer value1, Integer value2) {
            addCriterion("money_lock not between", value1, value2, "moneyLock");
            return (Criteria) this;
        }

        public Criteria andZfbAccountIsNull() {
            addCriterion("zfb_account is null");
            return (Criteria) this;
        }

        public Criteria andZfbAccountIsNotNull() {
            addCriterion("zfb_account is not null");
            return (Criteria) this;
        }

        public Criteria andZfbAccountEqualTo(String value) {
            addCriterion("zfb_account =", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountNotEqualTo(String value) {
            addCriterion("zfb_account <>", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountGreaterThan(String value) {
            addCriterion("zfb_account >", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountGreaterThanOrEqualTo(String value) {
            addCriterion("zfb_account >=", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountLessThan(String value) {
            addCriterion("zfb_account <", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountLessThanOrEqualTo(String value) {
            addCriterion("zfb_account <=", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountLike(String value) {
            addCriterion("zfb_account like", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountNotLike(String value) {
            addCriterion("zfb_account not like", value, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountIn(List<String> values) {
            addCriterion("zfb_account in", values, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountNotIn(List<String> values) {
            addCriterion("zfb_account not in", values, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountBetween(String value1, String value2) {
            addCriterion("zfb_account between", value1, value2, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andZfbAccountNotBetween(String value1, String value2) {
            addCriterion("zfb_account not between", value1, value2, "zfbAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountIsNull() {
            addCriterion("weixin_account is null");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountIsNotNull() {
            addCriterion("weixin_account is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountEqualTo(String value) {
            addCriterion("weixin_account =", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotEqualTo(String value) {
            addCriterion("weixin_account <>", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountGreaterThan(String value) {
            addCriterion("weixin_account >", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountGreaterThanOrEqualTo(String value) {
            addCriterion("weixin_account >=", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountLessThan(String value) {
            addCriterion("weixin_account <", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountLessThanOrEqualTo(String value) {
            addCriterion("weixin_account <=", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountLike(String value) {
            addCriterion("weixin_account like", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotLike(String value) {
            addCriterion("weixin_account not like", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountIn(List<String> values) {
            addCriterion("weixin_account in", values, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotIn(List<String> values) {
            addCriterion("weixin_account not in", values, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountBetween(String value1, String value2) {
            addCriterion("weixin_account between", value1, value2, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotBetween(String value1, String value2) {
            addCriterion("weixin_account not between", value1, value2, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_assist
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}