package cn.taiqiu8.model;

import java.util.Date;

public class AssistOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.assist_id
     *
     * @mbggenerated
     */
    private Integer assistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.prepay
     *
     * @mbggenerated
     */
    private Integer prepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.paytype
     *
     * @mbggenerated
     */
    private Short paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.broadcast
     *
     * @mbggenerated
     */
    private Short broadcast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.club
     *
     * @mbggenerated
     */
    private String club;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.star
     *
     * @mbggenerated
     */
    private Integer star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.confirm_time
     *
     * @mbggenerated
     */
    private Date confirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_order.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    public AssistOrder(Integer id, Integer customerId, Integer assistId, Integer money, Integer prepay, Short paytype, Short broadcast, String location, String club, Integer star, Date createTime, Date confirmTime, Short status) {
        this.id = id;
        this.customerId = customerId;
        this.assistId = assistId;
        this.money = money;
        this.prepay = prepay;
        this.paytype = paytype;
        this.broadcast = broadcast;
        this.location = location;
        this.club = club;
        this.star = star;
        this.createTime = createTime;
        this.confirmTime = confirmTime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    public AssistOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.id
     *
     * @return the value of assist_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.id
     *
     * @param id the value for assist_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.customer_id
     *
     * @return the value of assist_order.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.customer_id
     *
     * @param customerId the value for assist_order.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.assist_id
     *
     * @return the value of assist_order.assist_id
     *
     * @mbggenerated
     */
    public Integer getAssistId() {
        return assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.assist_id
     *
     * @param assistId the value for assist_order.assist_id
     *
     * @mbggenerated
     */
    public void setAssistId(Integer assistId) {
        this.assistId = assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.money
     *
     * @return the value of assist_order.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.money
     *
     * @param money the value for assist_order.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.prepay
     *
     * @return the value of assist_order.prepay
     *
     * @mbggenerated
     */
    public Integer getPrepay() {
        return prepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.prepay
     *
     * @param prepay the value for assist_order.prepay
     *
     * @mbggenerated
     */
    public void setPrepay(Integer prepay) {
        this.prepay = prepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.paytype
     *
     * @return the value of assist_order.paytype
     *
     * @mbggenerated
     */
    public Short getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.paytype
     *
     * @param paytype the value for assist_order.paytype
     *
     * @mbggenerated
     */
    public void setPaytype(Short paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.broadcast
     *
     * @return the value of assist_order.broadcast
     *
     * @mbggenerated
     */
    public Short getBroadcast() {
        return broadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.broadcast
     *
     * @param broadcast the value for assist_order.broadcast
     *
     * @mbggenerated
     */
    public void setBroadcast(Short broadcast) {
        this.broadcast = broadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.location
     *
     * @return the value of assist_order.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.location
     *
     * @param location the value for assist_order.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.club
     *
     * @return the value of assist_order.club
     *
     * @mbggenerated
     */
    public String getClub() {
        return club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.club
     *
     * @param club the value for assist_order.club
     *
     * @mbggenerated
     */
    public void setClub(String club) {
        this.club = club == null ? null : club.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.star
     *
     * @return the value of assist_order.star
     *
     * @mbggenerated
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.star
     *
     * @param star the value for assist_order.star
     *
     * @mbggenerated
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.create_time
     *
     * @return the value of assist_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.create_time
     *
     * @param createTime the value for assist_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.confirm_time
     *
     * @return the value of assist_order.confirm_time
     *
     * @mbggenerated
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.confirm_time
     *
     * @param confirmTime the value for assist_order.confirm_time
     *
     * @mbggenerated
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_order.status
     *
     * @return the value of assist_order.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_order.status
     *
     * @param status the value for assist_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}