package cn.taiqiu8.model;

import java.util.Date;

public class ChargeOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.before
     *
     * @mbggenerated
     */
    private Integer before;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.after
     *
     * @mbggenerated
     */
    private Integer after;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    public ChargeOrder(Integer id, Integer userId, Integer amount, Integer before, Integer after, Integer status, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.amount = amount;
        this.before = before;
        this.after = after;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    public ChargeOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.id
     *
     * @return the value of charge_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.id
     *
     * @param id the value for charge_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.user_id
     *
     * @return the value of charge_order.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.user_id
     *
     * @param userId the value for charge_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.amount
     *
     * @return the value of charge_order.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.amount
     *
     * @param amount the value for charge_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.before
     *
     * @return the value of charge_order.before
     *
     * @mbggenerated
     */
    public Integer getBefore() {
        return before;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.before
     *
     * @param before the value for charge_order.before
     *
     * @mbggenerated
     */
    public void setBefore(Integer before) {
        this.before = before;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.after
     *
     * @return the value of charge_order.after
     *
     * @mbggenerated
     */
    public Integer getAfter() {
        return after;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.after
     *
     * @param after the value for charge_order.after
     *
     * @mbggenerated
     */
    public void setAfter(Integer after) {
        this.after = after;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.status
     *
     * @return the value of charge_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.status
     *
     * @param status the value for charge_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.create_time
     *
     * @return the value of charge_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.create_time
     *
     * @param createTime the value for charge_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_order.update_time
     *
     * @return the value of charge_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_order.update_time
     *
     * @param updateTime the value for charge_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}