package cn.taiqiu8.model;

import java.util.Date;

public class UserAttention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention.initiative_id
     *
     * @mbggenerated
     */
    private Integer initiativeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention.passive_id
     *
     * @mbggenerated
     */
    private Integer passiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    public UserAttention(Integer id, Integer initiativeId, Integer passiveId, Short type, Date createdTime, Date updateTime) {
        this.id = id;
        this.initiativeId = initiativeId;
        this.passiveId = passiveId;
        this.type = type;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    public UserAttention() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention.id
     *
     * @return the value of user_attention.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention.id
     *
     * @param id the value for user_attention.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention.initiative_id
     *
     * @return the value of user_attention.initiative_id
     *
     * @mbggenerated
     */
    public Integer getInitiativeId() {
        return initiativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention.initiative_id
     *
     * @param initiativeId the value for user_attention.initiative_id
     *
     * @mbggenerated
     */
    public void setInitiativeId(Integer initiativeId) {
        this.initiativeId = initiativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention.passive_id
     *
     * @return the value of user_attention.passive_id
     *
     * @mbggenerated
     */
    public Integer getPassiveId() {
        return passiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention.passive_id
     *
     * @param passiveId the value for user_attention.passive_id
     *
     * @mbggenerated
     */
    public void setPassiveId(Integer passiveId) {
        this.passiveId = passiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention.type
     *
     * @return the value of user_attention.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention.type
     *
     * @param type the value for user_attention.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention.created_time
     *
     * @return the value of user_attention.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention.created_time
     *
     * @param createdTime the value for user_attention.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention.update_time
     *
     * @return the value of user_attention.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention.update_time
     *
     * @param updateTime the value for user_attention.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}