package cn.taiqiu8.model;

import java.util.Date;

public class WithdrawlOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.money_account
     *
     * @mbggenerated
     */
    private String moneyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.fee
     *
     * @mbggenerated
     */
    private Integer fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.amount_tax_before
     *
     * @mbggenerated
     */
    private Integer amountTaxBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.amount_tax_after
     *
     * @mbggenerated
     */
    private Integer amountTaxAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.money_before
     *
     * @mbggenerated
     */
    private Integer moneyBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.money_after
     *
     * @mbggenerated
     */
    private Integer moneyAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawl_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    public WithdrawlOrder(Integer id, Integer userId, String moneyAccount, Integer amount, Integer fee, Integer amountTaxBefore, Integer amountTaxAfter, Integer moneyBefore, Integer moneyAfter, Short status, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.moneyAccount = moneyAccount;
        this.amount = amount;
        this.fee = fee;
        this.amountTaxBefore = amountTaxBefore;
        this.amountTaxAfter = amountTaxAfter;
        this.moneyBefore = moneyBefore;
        this.moneyAfter = moneyAfter;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    public WithdrawlOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.id
     *
     * @return the value of withdrawl_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.id
     *
     * @param id the value for withdrawl_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.user_id
     *
     * @return the value of withdrawl_order.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.user_id
     *
     * @param userId the value for withdrawl_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.money_account
     *
     * @return the value of withdrawl_order.money_account
     *
     * @mbggenerated
     */
    public String getMoneyAccount() {
        return moneyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.money_account
     *
     * @param moneyAccount the value for withdrawl_order.money_account
     *
     * @mbggenerated
     */
    public void setMoneyAccount(String moneyAccount) {
        this.moneyAccount = moneyAccount == null ? null : moneyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.amount
     *
     * @return the value of withdrawl_order.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.amount
     *
     * @param amount the value for withdrawl_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.fee
     *
     * @return the value of withdrawl_order.fee
     *
     * @mbggenerated
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.fee
     *
     * @param fee the value for withdrawl_order.fee
     *
     * @mbggenerated
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.amount_tax_before
     *
     * @return the value of withdrawl_order.amount_tax_before
     *
     * @mbggenerated
     */
    public Integer getAmountTaxBefore() {
        return amountTaxBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.amount_tax_before
     *
     * @param amountTaxBefore the value for withdrawl_order.amount_tax_before
     *
     * @mbggenerated
     */
    public void setAmountTaxBefore(Integer amountTaxBefore) {
        this.amountTaxBefore = amountTaxBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.amount_tax_after
     *
     * @return the value of withdrawl_order.amount_tax_after
     *
     * @mbggenerated
     */
    public Integer getAmountTaxAfter() {
        return amountTaxAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.amount_tax_after
     *
     * @param amountTaxAfter the value for withdrawl_order.amount_tax_after
     *
     * @mbggenerated
     */
    public void setAmountTaxAfter(Integer amountTaxAfter) {
        this.amountTaxAfter = amountTaxAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.money_before
     *
     * @return the value of withdrawl_order.money_before
     *
     * @mbggenerated
     */
    public Integer getMoneyBefore() {
        return moneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.money_before
     *
     * @param moneyBefore the value for withdrawl_order.money_before
     *
     * @mbggenerated
     */
    public void setMoneyBefore(Integer moneyBefore) {
        this.moneyBefore = moneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.money_after
     *
     * @return the value of withdrawl_order.money_after
     *
     * @mbggenerated
     */
    public Integer getMoneyAfter() {
        return moneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.money_after
     *
     * @param moneyAfter the value for withdrawl_order.money_after
     *
     * @mbggenerated
     */
    public void setMoneyAfter(Integer moneyAfter) {
        this.moneyAfter = moneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.status
     *
     * @return the value of withdrawl_order.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.status
     *
     * @param status the value for withdrawl_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.create_time
     *
     * @return the value of withdrawl_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.create_time
     *
     * @param createTime the value for withdrawl_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawl_order.update_time
     *
     * @return the value of withdrawl_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawl_order.update_time
     *
     * @param updateTime the value for withdrawl_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}