package cn.taiqiu8.dao;

import cn.taiqiu8.model.AssistOrderEvaluation;
import cn.taiqiu8.model.AssistOrderEvaluationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssistOrderEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int countByExample(AssistOrderEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int deleteByExample(AssistOrderEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int insert(AssistOrderEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int insertSelective(AssistOrderEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    List<AssistOrderEvaluation> selectByExample(AssistOrderEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    AssistOrderEvaluation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssistOrderEvaluation record, @Param("example") AssistOrderEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssistOrderEvaluation record, @Param("example") AssistOrderEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssistOrderEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssistOrderEvaluation record);
}