package cn.taiqiu8.dao;

import cn.taiqiu8.model.AssistOrder;
import cn.taiqiu8.model.AssistOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssistOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int countByExample(AssistOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int deleteByExample(AssistOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int insert(AssistOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int insertSelective(AssistOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    List<AssistOrder> selectByExample(AssistOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    AssistOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssistOrder record, @Param("example") AssistOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssistOrder record, @Param("example") AssistOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssistOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssistOrder record);
}