package cn.taiqiu8.dao;

import cn.taiqiu8.model.ChargeOrder;
import cn.taiqiu8.model.ChargeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int countByExample(ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int deleteByExample(ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int insert(ChargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int insertSelective(ChargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    List<ChargeOrder> selectByExample(ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    ChargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChargeOrder record, @Param("example") ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChargeOrder record, @Param("example") ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChargeOrder record);
}