package cn.taiqiu8.dao;

import cn.taiqiu8.model.UserAssist;
import cn.taiqiu8.model.UserAssistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAssistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int countByExample(UserAssistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int deleteByExample(UserAssistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int insert(UserAssist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int insertSelective(UserAssist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    List<UserAssist> selectByExample(UserAssistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    UserAssist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAssist record, @Param("example") UserAssistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAssist record, @Param("example") UserAssistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAssist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_assist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAssist record);
}