package cn.taiqiu8.dao;

import cn.taiqiu8.model.AssistEvaluation;
import cn.taiqiu8.model.AssistEvaluationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssistEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int countByExample(AssistEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int deleteByExample(AssistEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int insert(AssistEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int insertSelective(AssistEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    List<AssistEvaluation> selectByExample(AssistEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    AssistEvaluation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssistEvaluation record, @Param("example") AssistEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssistEvaluation record, @Param("example") AssistEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssistEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssistEvaluation record);
}