package cn.taiqiu8.dao;

import cn.taiqiu8.model.AssistAlbum;
import cn.taiqiu8.model.AssistAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssistAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int countByExample(AssistAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int deleteByExample(AssistAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int insert(AssistAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int insertSelective(AssistAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    List<AssistAlbum> selectByExample(AssistAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    AssistAlbum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssistAlbum record, @Param("example") AssistAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssistAlbum record, @Param("example") AssistAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssistAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssistAlbum record);
}