package cn.taiqiu8.dao;

import cn.taiqiu8.model.WithdrawlOrder;
import cn.taiqiu8.model.WithdrawlOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithdrawlOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int countByExample(WithdrawlOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int deleteByExample(WithdrawlOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int insert(WithdrawlOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int insertSelective(WithdrawlOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    List<WithdrawlOrder> selectByExample(WithdrawlOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    WithdrawlOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WithdrawlOrder record, @Param("example") WithdrawlOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WithdrawlOrder record, @Param("example") WithdrawlOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WithdrawlOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawl_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WithdrawlOrder record);
}